### ISSUE TITLE
Error on `jekyll serve`

### ISSUE THREAD

**Issue by rafaeleyng** [codeheaven-io/codeheaven.io#26]
I started to have an error when running `jekyll serve`. I tried several things but none solved. Then I tried to remove the project and install it again, following the instructions in README.

Now I have this problem, after `jekyll serve`:

```
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/rafael/code/codeheaven/codeheaven.io/_config.yml
/Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- octopress-escape-code (LoadError)
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
    from /Users/rafael/.rbenv/versions/2.1.2/bin/jekyll:23:in `load'
    from /Users/rafael/.rbenv/versions/2.1.2/bin/jekyll:23:in `<main>'
```

I'll be looking at it now. Would be nice to know whether somebody else is having this error.

This error started to happen after I changed A LOT of things in my machine, like dotfiles, changed from nvm to rbenv etc.

**Comment by rafaeleyng** [comment]
The site will work if instead of `jekyll serve` I run `bundle exec jekyll serve`

The idea came from this issue: https://github.com/octopress/octopress/issues/102

**Comment by rafaeleyng** [comment]
I have some seemingly related erros when running `rake production`.

```
$ rake production

Executing jekyll build
WARN: Unresolved specs during Gem::Specification.reset:
      rouge (~> 1.7)
      jekyll-watch (~> 1.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/rafael/code/codeheaven/codeheaven.io/_config.yml
/Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- octopress-escape-code (LoadError)
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_gems'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/rafael/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
    from /Users/rafael/.rbenv/versions/2.1.2/bin/jekyll:23:in `load'
    from /Users/rafael/.rbenv/versions/2.1.2/bin/jekyll:23:in `<main>'
rake aborted!
Error while running jekyll build
/Users/rafael/code/codeheaven/codeheaven.io/Rakefile:15:in `execute_jekyll_build'
/Users/rafael/code/codeheaven/codeheaven.io/Rakefile:6:in `block in <top (required)>'
Tasks: TOP => production
(See full trace by running task with --trace)
```

I tried some things, but none worked:

```
$ bundle exec rake production

-------------------------------------------------------
Please install s3_website with 'gem install s3_website'
-------------------------------------------------------
rake aborted!
cannot load such file -- s3_website
/Users/rafael/code/codeheaven/codeheaven.io/Rakefile:34:in `require'
/Users/rafael/code/codeheaven/codeheaven.io/Rakefile:34:in `ensure_s3_website_is_installed'
/Users/rafael/code/codeheaven/codeheaven.io/Rakefile:4:in `block in <top (required)>'
Tasks: TOP => production
(See full trace by running task with --trace)
```

Then:

```
$ gem install s3_website

Successfully installed s3_website-2.12.2
1 gem installed
```

But it didn't change anything. I also tried:

```
$ bundle exec gem install s3_website

Successfully installed thor-0.19.1
Successfully installed dotenv-1.0.2
Successfully installed deep_merge-1.0.0
Successfully installed configure-s3-website-1.7.1
Successfully installed colored-1.2
Successfully installed s3_website-2.12.2
6 gems installed
```

and didn't work. Probably doesn't even make sense.

**Comment by rafaeleyng** [comment]
I've uninstalled everything Ruby-related from my system, and reinstalled everything back again, and now it works.

Closing
